# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]

env:
  BUNDLE_NAME: Test-app.app

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: ./build-dev-app.sh

    - name: Store app as ${{ env.BUNDLE_NAME }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BUNDLE_NAME }}
        path: /Users/runner/work/training-gitgub-actions/training-gitgub-actions/build/Build/Products/Release-iphonesimulator/Task1-Dev.app

